### ISSUE TITLE
Blog title editable with Carbon

### ISSUE THREAD

**Issue by Fahme** [manshar/manshar#224] opened 2016-01-21 09:59 UTC
Writing a new blog title in Manshar can be styled !
![screen shot 2016-01-21 at 1 07 54 pm](https://cloud.githubusercontent.com/assets/10753722/12477346/0e2d9af6-c040-11e5-9a6e-d14540357ae6.png)

**Comment by mkhatib** [comment] 2016-01-23 01:37
This is the intended behavior we want to leave to the user the formatting of their articles. However we had a bug with how we extract the title and snippets that caused the title to be set to `null` sometimes and the snippets to be too short. This is now fixed and will be deployed shortly.

If the article has a title as the first thing of the article, we'll display that as a title in the listing pages. Otherwise the listing item will not have a title and only show the snippet from the article.

**Closed by mkhatib** 2016-01-23 01:37 UTC
